namespace SpellParser
{
    internal class Skill
    {
        public static string SpellSkill(double skill)
        {
            return skill switch
            {
                -1 => "Hit", // weapons/archery/backstab/frenzy/kick/etc..
                0 => "1H Blunt",
                1 => "1H Slash",
                2 => "2H Blunt",
                3 => "2H Slash",
                4 => "Abjuration",
                5 => "Alteration",
                6 => "Apply Poison",
                7 => "Archery",
                8 => "Backstab",
                9 => "Bind Wound",
                10 => "Bash",
                11 => "Block",
                12 => "Brass",
                13 => "Channeling",
                14 => "Conjuration",
                15 => "Defense",
                16 => "Disarm",
                17 => "Disarm Traps",
                18 => "Divination",
                19 => "Dodge",
                20 => "Double Attack",
                21 => "Dragon Punch",
                22 => "Dual Wield",
                23 => "Eagle Strike",
                24 => "Evocation",
                25 => "Feign Death",
                26 => "Flying Kick",
                27 => "Forage",
                28 => "Hand to Hand",
                29 => "Hide",
                30 => "Kick",
                31 => "Meditate",
                32 => "Mend",
                33 => "Offense",
                34 => "Parry",
                35 => "Pick Lock",
                36 => "1H Pierce",
                37 => "Riposte",
                38 => "Round Kick",
                39 => "Safe Fall",
                40 => "Sense Heading",
                41 => "Singing",
                42 => "Sneak",
                43 => "Specialize Abjuration",
                44 => "Specialize Alteration",
                45 => "Specialize Conjuration",
                46 => "Specialize Divination",
                47 => "Specialize Evocation",
                48 => "Pick Pockets",
                49 => "Stringed",
                50 => "Swimming",
                51 => "Throwing",
                52 => "Tiger Claw",
                53 => "Tracking",
                54 => "Wind",
                55 => "Fishing",
                56 => "Make Poison",
                57 => "Tinkering",
                58 => "Research",
                59 => "Alchemy",
                60 => "Baking",
                61 => "Tailoring",
                62 => "Sense Traps",
                63 => "Blacksmithing",
                64 => "Fletching",
                65 => "Brewing",
                66 => "Alcohol Tolerance",
                67 => "Begging",
                68 => "Jewelry Making",
                69 => "Pottery",
                70 => "Percussion",
                71 => "Intimidation",
                72 => "Berserking",
                73 => "Taunt",
                74 => "Frenzy",
                75 => "Remove Trap",
                76 => "Triple Attack",
                77 => "2H Pierce",
                98 => "Melee",
                105 => "Harm Touch",
                107 => "Lay Hands",
                111 => "Slam",
                114 => "Inspect Chest",
                115 => "Open Chest",
                116 => "Reveal Trap Chest",
                _ => "UNKNOWN SKILL",
            };

        }
    }
}
